### ISSUE TITLE
Example of using nginx ingress controller with TLS termination on Load balancer

### ISSUE THREAD

**Issue by tatupesonen** [UpCloudLtd/uks-beta#25]
Hey there!

We've been testing out UpCloud Managed Kubernetes and it's pretty great. Everything has worked well for the most part, but some examples of configuring TLS with ingress-nginx could be useful!

```mermaid
graph LR
        A[Clients] -- HTTPS 443 --> LB{*.upcloudlb.com}
        LB -- TLS terminated on Load Balancer --> nginx([ingress-nginx])
        nginx -- HTTP 80 --> serviceA
       nginx -- HTTP 80 --> serviceB
```

This is the setup we're trying to accomplish. Here's an example Ingress configuration of ours:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: application-svc
            port:
              number: 80  
```
```yaml
apiVersion: v1
kind: Service
metadata: 
  labels:
    app: application
  name: application
  annotations: {}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  selector:
    app: application
```

This routes HTTP traffic properly, but our application needs HTTPS to function. Using this configuration gives us `The plain HTTP request was sent to HTTPS port`.
